### ISSUE TITLE
Criar modelo conceitual e lógico do Banco de dados

### ISSUE THREAD

**Issue by italo-carvavalho** [italo-carvavalho/Saves-App#2]
<h1>Modelagem de dados. </h1>
<h2>Modelo conceitual e lógico</h2>
<p>Eu como desenvolvedor quero criar os modelos conceituais e lógicos de acordo com as propostas de funcionalidades do sistema para entender o plano de negócios junto aos outros stakeholders</p>

**Comment by joaopaulops** [comment]
![Screenshot_159](https://user-images.githubusercontent.com/16047633/138358904-b4b74663-efce-4c8a-bb02-7d996c838b34.png)

**Comment by joaopaulops** [comment]
![Screenshot_158](https://user-images.githubusercontent.com/16047633/138359155-5963a9a8-0a6b-4c93-959e-69515383b16f.png)
![Screenshot_161](https://user-images.githubusercontent.com/16047633/138361640-d7005337-93d1-492c-a4cb-a38b80816b82.png)

**Comment by lilialnas** [comment]
Observações: 
1. Iremos precisar de mais informações básicas (atributos) do usuário e do prestador.
2. Aconselho fortemente que tenhamos uma tabela de tipo de serviço onde um prestador pode prestar vários serviços.
Exemplo: eu posso trabalhar com pintura, elétrica e gesso. E podemos ter vários profissionais que sejam pintores, pedreiros.
3.  A contratação do serviço é importante ter uma data de criação. Afinal, eu preciso saber quando foi que eu contratei aquele serviço. Inclusive eu posso chamar uma pessoa para fazer o mesmo serviço várias vezes. 
4. É importante vocês pensarem que um serviço vai ter um ciclo de vida (nasce, cresce e morre). Novo, em andamento e finalizado. Pelo menos isso.
5. Futuramente, os usuários irão querer saber quais serviços foram feitos ou contratados.
6. É importante que tenha um feedback em cada serviço realizado e contabilização de pontos (gameficação). Vocês me falaram que teriam.  Os pontos serão do prestador de serviço e do usuário. Bons prestadores de serviço e bons clientes acredito que devam ser recompensados.
Suave??

**Comment by enrell** [comment]
![Captura de Tela (177)](https://user-images.githubusercontent.com/60587839/148601248-693f0c99-cb38-420b-a4cd-252487c74d17.png)
Modelo atualizado

**Comment by enrell** [comment]
Ultimo modelo lógico:
![Captura de Tela (187)](https://user-images.githubusercontent.com/60587839/150026452-55f44c71-9128-44d2-8b20-60bee00fe2c1.png)
