### ISSUE TITLE
Estilizar CRUD do cadastro do profissional.

### ISSUE THREAD

**Issue by enrell** [italo-carvavalho/Saves-App#29]

**Comment by joaopaulops** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/16047633/148276607-72933b99-ebc1-4962-9388-c109a8a3e5a0.png)

**Comment by joaopaulops** [comment]
Concluído

**Comment by joaopaulops** [comment]
https://github.com/italo-carvavalho/Saves-App/issues/30#issuecomment-1006016369
