### ISSUE TITLE
Criar protótipo de design de média fidelidade.

### ISSUE THREAD

**Issue by enrell** [italo-carvavalho/Saves-App#3]
<h1>Protótipo de média fidelidade</h1>
<p>Eu como desenvolvedor quero criar um protótipo focado somente no design, como paleta de cores, Grid, identidade visual, para possibilitar um melhor direcionamento na hora de codar.</p>

**Comment by enrell** [comment]
Protótipo do design pronto

**Comment by henribeiro** [comment]
Protótipo de média fidelidade criado no figma. Ainda faltam algumas páginas e modificar as cores da página

**Comment by lilialnas** [comment]
Link do protótipo. Não podemos fechar uma issue se ela não está finalizada.

**Comment by enrell** [comment]
[link do protótipo do figma](https://www.figma.com/file/lZ3VQHohjLOvfKFVItili0/Home-Page?node-id=3%3A4)
