### ISSUE TITLE
Criar modelo físico de banco de dados

### ISSUE THREAD

**Issue by ivan-teotonio** [italo-carvavalho/Saves-App#4]
<h1>Modelagem de dados </h1>
<h2>Modelo físico do banco de dados</h2>
Eu como desenvolvedor quero criar o modelo físico do banco de dados no mysql para criar, ler, atualizar e deletar (CRUD) dados do banco.

**Comment by enrell** [comment]
Modelo atualizad
![Captura de Tela (177)](https://user-images.githubusercontent.com/60587839/150026128-4bb8069d-3e54-4d1e-9100-258d3e6e20a1.png)
o

**Comment by enrell** [comment]
Modelo re-atualizado:
![Captura de Tela (187)](https://user-images.githubusercontent.com/60587839/150026317-607a1fd1-0da5-435e-a638-04069cd7ad89.png)
